let TeamNameMap = new Map();

TeamNameMap.set("BUF", "Buffalo Bills")
TeamNameMap.set("MIA", "Miami Dolphins")
TeamNameMap.set("NE", "New England Patriots")
TeamNameMap.set("NYJ", "New York Jets")
TeamNameMap.set("PIT", "Pittsburgh Steelers")
TeamNameMap.set("BAL", "Baltimore Ravens")
TeamNameMap.set("CLE", "Cleveland Browns")
TeamNameMap.set("CIN", "Cincinnati Bengals")
TeamNameMap.set("TEN", "Tennessee Titans")
TeamNameMap.set("IND", "Indianapolis Colts")
TeamNameMap.set("HOU", "Houston Texans")
TeamNameMap.set("JAX", "Jacksonville Jaguars")
TeamNameMap.set("KC", "Kansas City Chiefs")
TeamNameMap.set("LV", "Las Vegas Raiders")
TeamNameMap.set("LAC", "Los Angeles Chargers")
TeamNameMap.set("DEN", "Denver Broncos")

TeamNameMap.set("PHI", "Philadelphia Eagles")
TeamNameMap.set("WAS", "Washington")
TeamNameMap.set("DAL", "Dallas Cowboys")
TeamNameMap.set("NYG", "New York Giants")
TeamNameMap.set("CHI", "Chicago Bears")
TeamNameMap.set("GB", "Green Bay Packers")
TeamNameMap.set("DET", "Detroit Lions")
TeamNameMap.set("MIN", "Minnesota Vikings")
TeamNameMap.set("TB", "Tampa Bay Buccaneers")
TeamNameMap.set("NO", "New Orleans Saints")
TeamNameMap.set("CAR", "Carolina Panthers")
TeamNameMap.set("ATL", "Atlanta Falcons")
TeamNameMap.set("SEA", "Seattle Seahawks")
TeamNameMap.set("ARI", "Arizona Cardinals")
TeamNameMap.set("LAR", "Los Angeles Rams")
TeamNameMap.set("SF", "San Francisco 49ers")

export default TeamNameMap;